[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.2"
edition = "2024"
license = "GPL-3.0-or-later"

[workspace.lints.rust]
unsafe_code = "deny"
warnings = "deny"

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "debuginfo"
