# Test targets. Kept under tests/ so test-only dependencies (such as the Qt Network
# fixture server in updater_menu_test.cpp) are reviewed as test code and never as
# production build configuration. Included from the root only when BUILD_TESTING.

find_package(Python3 REQUIRED COMPONENTS Interpreter)
choscordb_add_executable(choscordb-diagnostics-tests tests/desktop/diagnostics_service_test.cpp tests/desktop/diagnostics_legacy_lock.cpp)
target_link_libraries(choscordb-diagnostics-tests PRIVATE choscordb-diagnostics Qt6::Test)
add_test(NAME diagnostics COMMAND choscordb-diagnostics-tests)
add_test(NAME diagnostics-smoke COMMAND ${Python3_EXECUTABLE}
  ${CMAKE_CURRENT_SOURCE_DIR}/tests/desktop/diagnostics_smoke_test.py $<TARGET_FILE:choscordb>)
set_tests_properties(diagnostics-smoke PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
find_package(Qt6 6.8 REQUIRED COMPONENTS Network)
choscordb_add_executable(choscordb-updater-menu-tests tests/desktop/updater_menu_test.cpp desktop/app/updater_windows_linux.cpp)
target_compile_definitions(choscordb-updater-menu-tests PRIVATE
  CHOSCORDB_TEST_UPDATER_MENU
  CHOSCORDB_UPDATE_PUBLIC_KEY="tWwf5+4hAmilViw6CrynbGYUr5ISGt/4OOAKR5jm+0o="
  CHOSCORDB_UPDATE_BASE_URL="https://example.github.io/example/updates"
  CHOSCORDB_UPDATE_REPOSITORY="example/example")
target_link_libraries(choscordb-updater-menu-tests PRIVATE choscordb-desktop choscordb-update-metadata Qt6::Network Qt6::Concurrent Qt6::Test)
add_test(NAME updater-menu COMMAND choscordb-updater-menu-tests)
set_tests_properties(updater-menu PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")

if(WIN32)
  find_package(Python3 REQUIRED COMPONENTS Interpreter)
endif()
choscordb_add_executable(choscordb-secondary-design-tests tests/desktop/secondary_design_test.cpp)
target_link_libraries(choscordb-secondary-design-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME secondary-design COMMAND choscordb-secondary-design-tests)
set_tests_properties(secondary-design PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-typography-tests tests/desktop/typography_test.cpp)
target_link_libraries(choscordb-typography-tests PRIVATE choscordb-design-system Qt6::Test)
if(WIN32)
  add_test(NAME typography COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/scripts/ci/qt_test_output.py $<TARGET_FILE:choscordb-typography-tests>)
else()
  add_test(NAME typography COMMAND choscordb-typography-tests)
endif()
set_tests_properties(typography PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-icons-tests tests/desktop/icons_test.cpp)
target_link_libraries(choscordb-icons-tests PRIVATE choscordb-design-system Qt6::Test)
add_test(NAME icons COMMAND choscordb-icons-tests)
set_tests_properties(icons PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-modal-panel-tests tests/desktop/modal_panel_test.cpp)
target_link_libraries(choscordb-modal-panel-tests PRIVATE choscordb-design-system Qt6::Test)
add_test(NAME modal-panel COMMAND choscordb-modal-panel-tests)
set_tests_properties(modal-panel PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-control-style-tests tests/desktop/control_style_test.cpp tests/desktop/control_style_test.h tests/desktop/control_style_surfaces_test.cpp)
target_link_libraries(choscordb-control-style-tests PRIVATE choscordb-design-system Qt6::Test)
if(WIN32)
  add_test(NAME control-style COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/scripts/ci/qt_test_output.py $<TARGET_FILE:choscordb-control-style-tests>)
else()
  add_test(NAME control-style COMMAND choscordb-control-style-tests)
endif()
set_tests_properties(control-style PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-components-tests tests/desktop/components_test.cpp)
target_link_libraries(choscordb-components-tests PRIVATE choscordb-design-system Qt6::Test)
add_test(NAME components COMMAND choscordb-components-tests)
set_tests_properties(components PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-preview-tests tests/desktop/preview_test.cpp tests/desktop/preview_test.h tests/desktop/preview_quick_search_test.cpp tests/desktop/preview_specimens_test.cpp tests/desktop/preview_cell_test.cpp tests/desktop/preview_basic_controls_test.cpp tests/desktop/preview_toast_test.cpp tests/desktop/preview_json_text_view_test.cpp tests/desktop/preview_column_row_test.cpp tests/desktop/preview_tokens_test.cpp)
target_link_libraries(choscordb-preview-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME preview COMMAND choscordb-preview-tests)
set_tests_properties(preview PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-appearance-adapter-tests tests/desktop/appearance_adapter_test.cpp)
target_link_libraries(choscordb-appearance-adapter-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME appearance-adapter COMMAND choscordb-appearance-adapter-tests)
set_tests_properties(appearance-adapter PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-component-gallery desktop/tools/component_gallery.cpp)
target_link_libraries(choscordb-component-gallery PRIVATE choscordb-preview)
add_dependencies(choscordb-preview-tests choscordb-component-gallery)
choscordb_add_executable(choscordb-design-system-tests tests/desktop/design_system_test.cpp)
target_link_libraries(choscordb-design-system-tests PRIVATE choscordb-design-system Qt6::Test)
add_test(NAME design-system COMMAND choscordb-design-system-tests)
set_tests_properties(design-system PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-json-text-view-tests tests/desktop/json_text_view_test.cpp)
target_link_libraries(choscordb-json-text-view-tests PRIVATE choscordb-design-system Qt6::Test)
add_test(NAME json-text-view COMMAND choscordb-json-text-view-tests)
set_tests_properties(json-text-view PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-modern-ui-tests tests/desktop/modern_ui_test.cpp tests/desktop/modern_ui_test.h tests/desktop/modern_ui_quick_search_test.cpp tests/desktop/modern_ui_workspace_test.cpp tests/desktop/modern_ui_status_line_test.cpp tests/desktop/modern_ui_connections_test.cpp tests/desktop/modern_ui_diagnostics_test.cpp tests/desktop/diagnostics_legacy_lock.cpp)
target_link_libraries(choscordb-modern-ui-tests PRIVATE choscordb-desktop Qt6::Test)
if(WIN32)
  add_test(NAME modern-ui COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/scripts/ci/qt_test_output.py $<TARGET_FILE:choscordb-modern-ui-tests>)
else()
  add_test(NAME modern-ui COMMAND choscordb-modern-ui-tests)
endif()
# These event-loop tests assert asynchronous completion deadlines. Avoid
# competing native engines/keychain operations when CTest runs in parallel.
set_tests_properties(modern-ui PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen" RUN_SERIAL TRUE)
choscordb_add_executable(choscordb-result-copy-workspace-tests tests/desktop/result_copy_workspace_test.cpp)
target_link_libraries(choscordb-result-copy-workspace-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME result-copy-workspace COMMAND choscordb-result-copy-workspace-tests)
set_tests_properties(result-copy-workspace PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-query-settings-corruption-tests tests/desktop/query_settings_corruption_test.cpp)
target_link_libraries(choscordb-query-settings-corruption-tests PRIVATE choscordb-desktop Qt6::Test)
find_package(Python3 QUIET COMPONENTS Interpreter)
if(Python3_Interpreter_FOUND)
  add_test(NAME cpp-source-size COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/scripts/ci/cpp_size.py)
  add_test(NAME ui-source-policy COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/scripts/ci/ui_policy.py)
  add_test(NAME query-settings-corruption COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/scripts/integration/query_settings_fixture.py $<TARGET_FILE:choscordb-query-settings-corruption-tests>)
  set_tests_properties(query-settings-corruption PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
endif()
choscordb_add_executable(choscordb-query-settings-workspace-tests tests/desktop/query_settings_workspace_test.cpp)
target_link_libraries(choscordb-query-settings-workspace-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME query-settings-workspace COMMAND choscordb-query-settings-workspace-tests)
set_tests_properties(query-settings-workspace PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-query-settings-controller-tests tests/desktop/query_settings_controller_test.cpp)
target_link_libraries(choscordb-query-settings-controller-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME query-settings-controller COMMAND choscordb-query-settings-controller-tests)
set_tests_properties(query-settings-controller PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-query-options-tests tests/desktop/query_options_test.cpp)
target_link_libraries(choscordb-query-options-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME query-options COMMAND choscordb-query-options-tests)
set_tests_properties(query-options PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-query-settings-dialog-tests tests/desktop/query_settings_dialog_test.cpp)
target_link_libraries(choscordb-query-settings-dialog-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME query-settings-dialog COMMAND choscordb-query-settings-dialog-tests)
set_tests_properties(query-settings-dialog PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-disconnect-workspace-tests tests/desktop/disconnect_workspace_test.cpp)
target_link_libraries(choscordb-disconnect-workspace-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME disconnect-workspace COMMAND choscordb-disconnect-workspace-tests)
set_tests_properties(disconnect-workspace PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-navigator-sql-workspace-tests tests/desktop/navigator_sql_workspace_test.cpp tests/desktop/navigator_sql_workspace_test.h tests/desktop/navigator_saved_sql_workspace_test.cpp tests/desktop/navigator_recovery_workspace_test.cpp tests/desktop/navigator_object_workspace_test.cpp tests/desktop/navigator_object_action_workspace_test.cpp tests/desktop/navigator_json_workspace_test.cpp)
target_link_libraries(choscordb-navigator-sql-workspace-tests PRIVATE choscordb-desktop Qt6::Test)
if(WIN32)
  add_test(NAME navigator-sql-workspace COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/scripts/ci/qt_test_output.py $<TARGET_FILE:choscordb-navigator-sql-workspace-tests>)
else()
  add_test(NAME navigator-sql-workspace COMMAND choscordb-navigator-sql-workspace-tests)
endif()
set_tests_properties(navigator-sql-workspace PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-schema-sidebar-workspace-tests tests/desktop/schema_sidebar_workspace_test.cpp)
target_link_libraries(choscordb-schema-sidebar-workspace-tests PRIVATE choscordb-desktop Qt6::Test)
if(WIN32)
  add_test(NAME schema-sidebar-workspace COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/scripts/ci/qt_test_output.py $<TARGET_FILE:choscordb-schema-sidebar-workspace-tests>)
else()
  add_test(NAME schema-sidebar-workspace COMMAND choscordb-schema-sidebar-workspace-tests)
endif()
set_tests_properties(schema-sidebar-workspace PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-navigator-sql-tests tests/desktop/navigator_sql_test.cpp)
target_link_libraries(choscordb-navigator-sql-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME navigator-sql COMMAND choscordb-navigator-sql-tests)
set_tests_properties(navigator-sql PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-object-action-sql-tests tests/desktop/object_action_sql_test.cpp)
target_link_libraries(choscordb-object-action-sql-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME object-action-sql COMMAND choscordb-object-action-sql-tests)
set_tests_properties(object-action-sql PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-object-inspection-adapter-tests tests/desktop/object_inspection_adapter_test.cpp)
target_link_libraries(choscordb-object-inspection-adapter-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME object-inspection-adapter COMMAND choscordb-object-inspection-adapter-tests)
set_tests_properties(object-inspection-adapter PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-object-data-workspace-tests tests/desktop/object_data_workspace_test.cpp)
target_link_libraries(choscordb-object-data-workspace-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME object-data-workspace COMMAND choscordb-object-data-workspace-tests)
set_tests_properties(object-data-workspace PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-cell-edit-workspace-tests tests/desktop/cell_edit_workspace_test.cpp)
target_link_libraries(choscordb-cell-edit-workspace-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME cell-edit-workspace COMMAND choscordb-cell-edit-workspace-tests)
set_tests_properties(cell-edit-workspace PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-cell-edit-sql-workspace-tests tests/desktop/cell_edit_sql_workspace_test.cpp)
target_link_libraries(choscordb-cell-edit-sql-workspace-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME cell-edit-sql-workspace COMMAND choscordb-cell-edit-sql-workspace-tests)
set_tests_properties(cell-edit-sql-workspace PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-grid-edit-workspace-tests tests/desktop/grid_edit_workspace_test.cpp)
target_link_libraries(choscordb-grid-edit-workspace-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME grid-edit-workspace COMMAND choscordb-grid-edit-workspace-tests)
set_tests_properties(grid-edit-workspace PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-quick-filter-workspace-tests tests/desktop/quick_filter_workspace_test.cpp)
target_link_libraries(choscordb-quick-filter-workspace-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME quick-filter-workspace COMMAND choscordb-quick-filter-workspace-tests)
set_tests_properties(quick-filter-workspace PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-result-view-workspace-tests tests/desktop/result_view_workspace_test.cpp)
target_link_libraries(choscordb-result-view-workspace-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME result-view-workspace COMMAND choscordb-result-view-workspace-tests)
set_tests_properties(result-view-workspace PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-object-explorer-tests tests/desktop/object_explorer_test.cpp)
target_link_libraries(choscordb-object-explorer-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME object-explorer COMMAND choscordb-object-explorer-tests)
set_tests_properties(object-explorer PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-object-erd-navigation-tests tests/desktop/object_erd_navigation_test.cpp)
target_link_libraries(choscordb-object-erd-navigation-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME object-erd-navigation COMMAND choscordb-object-erd-navigation-tests)
set_tests_properties(object-erd-navigation PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-editor-completion-lifecycle-tests tests/desktop/editor_completion_lifecycle_test.cpp)
target_link_libraries(choscordb-editor-completion-lifecycle-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME editor-completion-lifecycle COMMAND choscordb-editor-completion-lifecycle-tests)
set_tests_properties(editor-completion-lifecycle PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-editor-completion-tests tests/desktop/editor_completion_test.cpp)
target_link_libraries(choscordb-editor-completion-tests PRIVATE choscordb-desktop Qt6::Test)
if(WIN32)
  add_test(NAME editor-completion COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/scripts/ci/qt_test_output.py $<TARGET_FILE:choscordb-editor-completion-tests>)
else()
  add_test(NAME editor-completion COMMAND choscordb-editor-completion-tests)
endif()
set_tests_properties(editor-completion PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-completion-service-tests tests/desktop/completion_service_test.cpp)
target_link_libraries(choscordb-completion-service-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME completion-service COMMAND choscordb-completion-service-tests)
set_tests_properties(completion-service PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-preferences-workspace-tests tests/desktop/preferences_workspace_test.cpp)
target_link_libraries(choscordb-preferences-workspace-tests PRIVATE choscordb-desktop Qt6::Test)
if(WIN32)
  add_test(NAME preferences-workspace COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/scripts/ci/qt_test_output.py $<TARGET_FILE:choscordb-preferences-workspace-tests>)
else()
  add_test(NAME preferences-workspace COMMAND choscordb-preferences-workspace-tests)
endif()
set_tests_properties(preferences-workspace PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-preferences-tests tests/desktop/preferences_test.cpp)
target_link_libraries(choscordb-preferences-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME preferences COMMAND choscordb-preferences-tests)
set_tests_properties(preferences PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-search-tests tests/desktop/search_test.cpp)
target_link_libraries(choscordb-search-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME search COMMAND choscordb-search-tests)
set_tests_properties(search PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-history-tests tests/desktop/history_test.cpp)
target_link_libraries(choscordb-history-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME history COMMAND choscordb-history-tests)
set_tests_properties(history PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-value-preview-model-tests tests/desktop/value_preview_model_test.cpp)
target_link_libraries(choscordb-value-preview-model-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME value-preview-model COMMAND choscordb-value-preview-model-tests)
set_tests_properties(value-preview-model PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-recovery-tests tests/desktop/recovery_test.cpp)
target_link_libraries(choscordb-recovery-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME recovery COMMAND choscordb-recovery-tests)
set_tests_properties(recovery PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-workspace-tests tests/desktop/workspace_test.cpp tests/desktop/workspace_test.h tests/desktop/workspace_results_test.cpp tests/desktop/workspace_profiles_test.cpp tests/desktop/connection_dialog_test.cpp tests/desktop/ssh_inline_key_test.cpp tests/desktop/ssh_host_key_test.cpp desktop/app/updater_disabled.cpp)
target_link_libraries(choscordb-workspace-tests PRIVATE choscordb-desktop Qt6::Test)
if(WIN32)
  add_test(NAME workspace COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/scripts/ci/qt_test_output.py $<TARGET_FILE:choscordb-workspace-tests>)
else()
  add_test(NAME workspace COMMAND choscordb-workspace-tests)
endif()
set_tests_properties(workspace PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
if(UNIX AND Python3_Interpreter_FOUND)
  add_test(NAME ssh-trust-ui-fixture COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/desktop/ssh_trust_fixture.py $<TARGET_FILE:choscordb-workspace-tests>)
  set_tests_properties(ssh-trust-ui-fixture PROPERTIES TIMEOUT 60 RUN_SERIAL TRUE)
endif()
choscordb_add_executable(choscordb-navigator-model-tests tests/desktop/navigator_model_test.cpp)
target_link_libraries(choscordb-navigator-model-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME navigator-model COMMAND choscordb-navigator-model-tests)
set_tests_properties(navigator-model PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-navigator-scale-tests tests/desktop/navigator_scale_test.cpp)
target_link_libraries(choscordb-navigator-scale-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME navigator-scale COMMAND choscordb-navigator-scale-tests)
set_tests_properties(navigator-scale PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-schema-sidebar-model-tests tests/desktop/schema_sidebar_model_test.cpp)
target_link_libraries(choscordb-schema-sidebar-model-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME schema-sidebar-model COMMAND choscordb-schema-sidebar-model-tests)
set_tests_properties(schema-sidebar-model PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-navigator-pin-model-tests tests/desktop/navigator_pin_model_test.cpp)
target_link_libraries(choscordb-navigator-pin-model-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME navigator-pin-model COMMAND choscordb-navigator-pin-model-tests)
set_tests_properties(navigator-pin-model PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-navigator-pin-resolve-tests tests/desktop/navigator_pin_resolve_test.cpp)
target_link_libraries(choscordb-navigator-pin-resolve-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME navigator-pin-resolve COMMAND choscordb-navigator-pin-resolve-tests)
set_tests_properties(navigator-pin-resolve PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-pinned-tree-model-tests tests/desktop/pinned_tree_model_test.cpp)
target_link_libraries(choscordb-pinned-tree-model-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME pinned-tree-model COMMAND choscordb-pinned-tree-model-tests)
set_tests_properties(pinned-tree-model PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-pinning-sidebar-tests tests/desktop/pinning_sidebar_test.cpp)
target_link_libraries(choscordb-pinning-sidebar-tests PRIVATE choscordb-desktop Qt6::Test)
if(WIN32)
  add_test(NAME pinning-sidebar COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/scripts/ci/qt_test_output.py $<TARGET_FILE:choscordb-pinning-sidebar-tests>)
else()
  add_test(NAME pinning-sidebar COMMAND choscordb-pinning-sidebar-tests)
endif()
set_tests_properties(pinning-sidebar PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-pinning-flow-tests tests/desktop/pinning_flow_test.cpp)
target_link_libraries(choscordb-pinning-flow-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME pinning-flow COMMAND choscordb-pinning-flow-tests)
set_tests_properties(pinning-flow PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-pin-store-tests tests/desktop/pin_store_test.cpp)
target_link_libraries(choscordb-pin-store-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME pin-store COMMAND choscordb-pin-store-tests)
set_tests_properties(pin-store PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-result-model-tests tests/desktop/result_model_test.cpp)
target_link_libraries(choscordb-result-model-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME result-model COMMAND choscordb-result-model-tests)
set_tests_properties(result-model PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
choscordb_add_executable(choscordb-editor-tests tests/desktop/editor_test.cpp)
target_link_libraries(choscordb-editor-tests PRIVATE choscordb-desktop Qt6::Test)
add_test(NAME editor COMMAND choscordb-editor-tests)
set_tests_properties(editor PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")

if(APPLE AND BUILD_TESTING)
  choscordb_add_executable(choscordb-macos-title-bar-tests tests/desktop/macos_title_bar_test.mm desktop/app/updater_disabled.cpp)
  target_link_libraries(choscordb-macos-title-bar-tests PRIVATE choscordb-desktop Qt6::Test "-framework AppKit")
  add_test(NAME macos-title-bar COMMAND choscordb-macos-title-bar-tests)
  set_tests_properties(macos-title-bar PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=cocoa")
endif()
