#pragma once

#include <QObject>

class PreviewTest final : public QObject {
    Q_OBJECT

  private slots:
    void codePreviewTextAreaUsesSharedVariantInBothThemes();
    void navigationTreeSpecimenUsesRealTreeInBothThemes();
    void columnRowSpecimenUsesRealDelegateInBothThemes();
    void switchSpecimenUsesRealControlsInBothThemes();
    void recentHistoryRowsUseSharedDelegateInBothThemes();
    void editorResultsSplitUsesEqualPanesInBothThemes();
    void documentTabSpecimenShowsFixedWidthTabsInBothThemes();
    void documentTabContentsSitAtVerticalCenterInBothThemes();
    void documentTabsShowKeyboardFocusInBothThemes();
    void tableHeadersCanBeDraggedInBothThemes();
    void dialogSectionsHaveMutedPaddedFooterInBothThemes();
    void modalSpecimenNamesTheDialogSurface();
    void workspaceToolbarSpecimenUsesMutedSurfaceInBothThemes();
    void statusLineSpecimenUsesSharedSurfaceInBothThemes();
    void richTextParagraphsHaveCompactSpacing();
    void showToastOpensTransientToastAtViewportCorner();
    void toastPortalIsPresentInBothThemes();
    void progressToastHasPersistentIndicatorInBothThemes();
    void toastCanAttachAcrossWidgetTrees();
    void windowToastClearsDestroyedModalOwner();
    void toastVariantsShowTitleBodyAndUseConfiguredTimeout();
    void pinnedToastKeepsPriorityAndRestoresLatestNotice();
    void dismissingPinnedToastPreservesLaterOrdinaryNotice();
    void pinnedToastSpecimenIsPresentInBothThemes();
    void nonmodalDialogSurfaceHasNoOutline();
    void nonmodalDialogGrowsWhenDescriptionWraps();
    void galleryOpenKeepsOverlayInsideWindow_data();
    void galleryOpenKeepsOverlayInsideWindow();
    void popupSpecimensStayInsideWindowInBothThemes();
    void selectPopupFitsRowsInBothThemes();
    void selectPopupStaysAttachedNearWindowBottom();
    void contextMenuSpecimenUsesCursorInBothThemes();
    void moreButtonUsesThemeSurface();
    void scrollSpecimensKeepTheirIndependentThemePaper();
    void narrowGalleryKeepsNavigationAndActionsReachable();
    void standaloneCapturesRequestedThemeAndViewport_data();
    void standaloneCapturesRequestedThemeAndViewport();
    void confirmationSpecimenUsesProductionCancellationBoundary();
    void rightSheetSpecimenUsesModalBoundaryInBothThemes();
    void quickSearchSpecimenUsesRealOverlayInBothThemes();
    void quickSearchRowsUseSuppliedIconAndRetintWhenThemeChanges();
    void quickSearchInteractionPreservesFocusAndSelection();
    void quickSearchKeepsSelectionAcrossResultUpdates();
    void tableHoverPreservesBackgroundInBothThemes();
    void typedTableSpecimenUsesSharedControlsInBothThemes();
    void choiceEditorSpecimenShowsRealControlInBothThemes();
    void typedTableDropdownAndLinkActionWorkThroughView();
    void resultTableActionTracksModelReplacement();
    void typedTableDropdownStagesSelection();
    void initTestCase();
    void exportedPopupContainsItsVisibleContent_data();
    void exportedPopupContainsItsVisibleContent();
    void tooltipUsesTheProductionSurfaceInBothThemes();
    void exportsRenderActualModalAndMenuSurfaces();
    void standaloneExportsWithoutAProfile();
    void displayedIconsRasterizeAtTargetScale_data();
    void displayedIconsRasterizeAtTargetScale();
    void iconsShowNamedProductionAssetsAtSupportedSizes();
    void examplesOpenActualDismissibleSurfaces();
    void fieldSpecimenRetainsEditingAndValidationStates();
    void sidebarTabSpecimenUsesProductionContextInBothThemes();
    void sidebarTabFocusRingSurvivesOnlyKeyboardActivation();
    void buttonsUseProductionVariantsAndStates();
    void individualSpecimensAreSelectableAndSearchable();
    void fieldValidationIsBelowInputAndSelectInBothThemes();
    void tokensExposeCopyableValuesAndSources();
    void exportsAreDeterministicAndFailuresVisible();
    void comparisonThemesAreIndependent();
    void navigationIsSearchable();
    void componentFamiliesAreRendered();
    void dialogSectionsPreviewUsesRealComponentInBothThemes();
    void navigationProfileRowsShowRegularAndSelectedStates();
    void dockSpecimenRendersThemedTitleAndButtons();
    void navigationTreeTogglesAndRenamesFromMenu();
};
