option(CHOSCORDB_PRODUCTION_RELEASE "Enable the signed macOS release updater" OFF)
option(CHOSCORDB_UPDATE_REHEARSAL "Enable the isolated signed update rehearsal" OFF)
set(CHOSCORDB_REHEARSAL_FEED_URL "" CACHE STRING "Isolated HTTPS rehearsal appcast URL")
set(CHOSCORDB_SPARKLE_FEED_URL "https://cdn.choscor.com/choscordb-appcast.xml" CACHE STRING "Production HTTPS appcast URL")
set(CHOSCORDB_SPARKLE_ROOT "" CACHE PATH "Verified Sparkle distribution prefix")
set(CHOSCORDB_SPARKLE_PUBLIC_KEY "" CACHE STRING "ChoscorDB public Ed25519 update key")
if(APPLE AND (CHOSCORDB_PRODUCTION_RELEASE OR CHOSCORDB_UPDATE_REHEARSAL))
  enable_language(OBJCXX)
endif()
function(choscordb_configure_updater target)
  if(CHOSCORDB_PRODUCTION_RELEASE AND CHOSCORDB_UPDATE_REHEARSAL)
    message(FATAL_ERROR "Production and update rehearsal are mutually exclusive")
  endif()
  if(NOT CHOSCORDB_PRODUCTION_RELEASE AND NOT CHOSCORDB_UPDATE_REHEARSAL)
    target_sources(${target} PRIVATE desktop/app/updater_disabled.cpp)
    _choscordb_register_first_party_target(${target} desktop/app/updater_disabled.cpp)
    return()
  endif()
  if(NOT APPLE OR BUILD_TESTING)
    message(FATAL_ERROR "Production updater requires macOS and BUILD_TESTING=OFF")
  endif()
  if(NOT CMAKE_OSX_ARCHITECTURES STREQUAL "arm64" OR NOT CMAKE_OSX_DEPLOYMENT_TARGET STREQUAL "26.0")
    message(FATAL_ERROR "Production requires arm64 and macOS deployment target 26.0")
  endif()
  string(LENGTH "${CHOSCORDB_SPARKLE_PUBLIC_KEY}" key_length)
  if(NOT key_length EQUAL 44 OR NOT CHOSCORDB_SPARKLE_PUBLIC_KEY MATCHES "^[A-Za-z0-9+/]+=$")
    message(FATAL_ERROR "Set CHOSCORDB_SPARKLE_PUBLIC_KEY to the app-specific public Ed25519 key")
  endif()
  set(CHOSCORDB_APP_ID "com.choscor.ChoscorDB")
  if(NOT CHOSCORDB_SPARKLE_FEED_URL MATCHES "^https://[A-Za-z0-9.-]+/[A-Za-z0-9/_.-]+$")
    message(FATAL_ERROR "Production appcast requires an HTTPS CHOSCORDB_SPARKLE_FEED_URL")
  endif()
  set(CHOSCORDB_UPDATE_FEED_URL "${CHOSCORDB_SPARKLE_FEED_URL}")
  if(CHOSCORDB_UPDATE_REHEARSAL)
    if(NOT CHOSCORDB_REHEARSAL_FEED_URL MATCHES "^https://[A-Za-z0-9.-]+/[A-Za-z0-9/_.-]+$"
       OR CHOSCORDB_REHEARSAL_FEED_URL STREQUAL CHOSCORDB_UPDATE_FEED_URL)
      message(FATAL_ERROR "Rehearsal requires a separate HTTPS CHOSCORDB_REHEARSAL_FEED_URL")
    endif()
    set(CHOSCORDB_APP_ID "com.choscor.ChoscorDB.tests.rehearsal")
    set(CHOSCORDB_UPDATE_FEED_URL "${CHOSCORDB_REHEARSAL_FEED_URL}")
  endif()
  target_compile_definitions(choscordb-desktop PUBLIC CHOSCORDB_APP_ID="${CHOSCORDB_APP_ID}")
  set_target_properties(${target} PROPERTIES MACOSX_BUNDLE_GUI_IDENTIFIER "${CHOSCORDB_APP_ID}")
  find_library(CHOSCORDB_SPARKLE_FRAMEWORK Sparkle PATHS "${CHOSCORDB_SPARKLE_ROOT}" NO_DEFAULT_PATH REQUIRED)
  target_sources(${target} PRIVATE desktop/app/updater_sparkle.mm)
  _choscordb_register_first_party_target(${target} desktop/app/updater_sparkle.mm)
  set_property(SOURCE desktop/app/updater_sparkle.mm APPEND PROPERTY COMPILE_OPTIONS "-fobjc-arc")
  target_link_libraries(${target} PRIVATE "${CHOSCORDB_SPARKLE_FRAMEWORK}")
  set_target_properties(${target} PROPERTIES OBJCXX_STANDARD 23 OBJCXX_STANDARD_REQUIRED ON)
  configure_file("${PROJECT_SOURCE_DIR}/desktop/app/Info.plist.in" "${PROJECT_BINARY_DIR}/ChoscorDB-Info.plist" @ONLY)
  set_target_properties(${target} PROPERTIES
    MACOSX_BUNDLE_INFO_PLIST "${PROJECT_BINARY_DIR}/ChoscorDB-Info.plist"
    BUILD_RPATH "@executable_path/../Frameworks"
    INSTALL_RPATH "@executable_path/../Frameworks")
  add_custom_command(TARGET ${target} POST_BUILD
    COMMAND /usr/bin/ditto "${CHOSCORDB_SPARKLE_FRAMEWORK}"
      "$<TARGET_BUNDLE_DIR:${target}>/Contents/Frameworks/Sparkle.framework"
    VERBATIM)
endfunction()
