option(CHOSCORDB_CROSS_PLATFORM_UPDATER "Enable signed Windows/Linux production updater" OFF)
set(CHOSCORDB_UPDATE_PUBLIC_KEY "" CACHE STRING "Dedicated Windows/Linux raw Ed25519 public key (base64)")
set(CHOSCORDB_UPDATE_BASE_URL "" CACHE STRING "Verified HTTPS Pages updates directory")
set(CHOSCORDB_UPDATE_REPOSITORY "" CACHE STRING "GitHub OWNER/REPO for immutable update assets")

function(choscordb_configure_windows_linux_updater target)
  if(APPLE)
    if(CHOSCORDB_CROSS_PLATFORM_UPDATER)
      message(FATAL_ERROR "Windows/Linux updater cannot be enabled on macOS")
    endif()
    return()
  endif()
  if(NOT CHOSCORDB_CROSS_PLATFORM_UPDATER)
    target_sources(${target} PRIVATE desktop/app/updater_disabled.cpp)
    _choscordb_register_first_party_target(${target} desktop/app/updater_disabled.cpp)
    return()
  endif()
  if(BUILD_TESTING)
    message(FATAL_ERROR "Production updater requires BUILD_TESTING=OFF")
  endif()
  if(NOT CHOSCORDB_UPDATE_PUBLIC_KEY MATCHES "^[A-Za-z0-9+/]{43}=$")
    message(FATAL_ERROR "Set CHOSCORDB_UPDATE_PUBLIC_KEY to the dedicated raw Ed25519 public key")
  endif()
  if(NOT CHOSCORDB_UPDATE_BASE_URL MATCHES "^https://[A-Za-z0-9.-]+/[A-Za-z0-9/_.-]+/updates$")
    message(FATAL_ERROR "Set CHOSCORDB_UPDATE_BASE_URL to the verified HTTPS Pages updates directory")
  endif()
  if(NOT CHOSCORDB_UPDATE_REPOSITORY MATCHES "^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")
    message(FATAL_ERROR "Set CHOSCORDB_UPDATE_REPOSITORY to OWNER/REPO")
  endif()
  string(REPLACE "/" ";" update_repository_parts "${CHOSCORDB_UPDATE_REPOSITORY}")
  list(GET update_repository_parts 0 update_owner)
  list(GET update_repository_parts 1 update_name)
  string(TOLOWER "${update_owner}" update_owner)
  string(TOLOWER "${update_name}" update_name)
  string(TOLOWER "${CHOSCORDB_UPDATE_BASE_URL}" update_base_lower)
  set(update_canonical_base "https://${update_owner}.github.io/${update_name}/updates")
  if(NOT update_base_lower STREQUAL update_canonical_base)
    message(FATAL_ERROR "Update Pages URL must belong to CHOSCORDB_UPDATE_REPOSITORY")
  endif()
  find_package(Qt6 6.8 REQUIRED COMPONENTS Network)
  target_sources(${target} PRIVATE desktop/app/updater_windows_linux.cpp)
  _choscordb_register_first_party_target(${target} desktop/app/updater_windows_linux.cpp)
  target_link_libraries(${target} PRIVATE choscordb-update-metadata Qt6::Network Qt6::Concurrent)
  target_compile_definitions(${target} PRIVATE
    CHOSCORDB_CROSS_PLATFORM_UPDATER
    CHOSCORDB_UPDATE_PUBLIC_KEY="${CHOSCORDB_UPDATE_PUBLIC_KEY}"
    CHOSCORDB_UPDATE_BASE_URL="${update_canonical_base}"
    CHOSCORDB_UPDATE_REPOSITORY="${CHOSCORDB_UPDATE_REPOSITORY}")
endfunction()
